[platformio]
description = Smart Home Voice Assistant — ESP32 DevKit V1

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
    -std=gnu++17

lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    bblanchon/ArduinoJson@^7.0.0

monitor_filters =
    time
